// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TblUser struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	// Encrypted password
	Password                        string           `json:"password"`
	AccessToken                     pgtype.Text      `json:"access_token"`
	Name                            pgtype.Text      `json:"name"`
	Altname                         pgtype.Text      `json:"altname"`
	Address                         pgtype.Text      `json:"address"`
	Email                           pgtype.Text      `json:"email"`
	Status                          int16            `json:"status"`
	Keyword                         pgtype.Text      `json:"keyword"`
	Shortcode                       pgtype.Int8      `json:"shortcode"`
	Description                     pgtype.Text      `json:"description"`
	LoginAttempts                   int64            `json:"login_attempts"`
	LastAtmptTime                   pgtype.Timestamp `json:"last_atmpt_time"`
	PwChangedTime                   pgtype.Timestamp `json:"pw_changed_time"`
	MobileNo                        pgtype.Text      `json:"mobile_no"`
	AclList                         []byte           `json:"acl_list"`
	LastLoginTime                   pgtype.Timestamp `json:"last_login_time"`
	CreateTime                      pgtype.Timestamp `json:"create_time"`
	UpdateTime                      pgtype.Timestamp `json:"update_time"`
	PushRate                        pgtype.Int8      `json:"push_rate"`
	MtPort                          string           `json:"mt_port"`
	OptOutTag                       pgtype.Text      `json:"opt_out_tag"`
	VatRegisteredNo                 pgtype.Text      `json:"vat_registered_no"`
	RoleID                          pgtype.Int8      `json:"role_id"`
	ApproverID                      pgtype.Int8      `json:"approver_id"`
	AdPolicy                        pgtype.Int2      `json:"ad_policy"`
	CreatedBy                       pgtype.Int8      `json:"created_by"`
	AcceptedTc                      int16            `json:"accepted_tc"`
	LockedTime                      pgtype.Timestamp `json:"locked_time"`
	OldPasswords                    pgtype.Text      `json:"old_passwords"`
	ForcePwChange                   pgtype.Int2      `json:"force_pw_change"`
	AllowInternational              int16            `json:"allow_international"`
	RateCardID                      pgtype.Int8      `json:"rate_card_id"`
	UserType                        int16            `json:"user_type"`
	DealerID                        pgtype.Int8      `json:"dealer_id"`
	AdminID                         pgtype.Int8      `json:"admin_id"`
	BLeadType                       pgtype.Int2      `json:"b_lead_type"`
	BLeadName                       pgtype.Text      `json:"b_lead_name"`
	InboxUrl                        pgtype.Text      `json:"inbox_url"`
	DeliveryUrl                     pgtype.Text      `json:"delivery_url"`
	InboxUrlType                    pgtype.Text      `json:"inbox_url_type"`
	DeliveryUrlType                 pgtype.Text      `json:"delivery_url_type"`
	ObdPort                         pgtype.Text      `json:"obd_port"`
	CampID                          pgtype.Int8      `json:"camp_id"`
	MaskingEnableForOtherOp         int16            `json:"masking_enable_for_other_op"`
	IndustryType                    pgtype.Int2      `json:"industry_type"`
	LeadID                          pgtype.Text      `json:"lead_id"`
	PcRate                          float64          `json:"pc_rate"`
	FinancialType                   pgtype.Int2      `json:"financial_type"`
	AllowCreditReimbursement        pgtype.Int2      `json:"allow_credit_reimbursement"`
	MidExpiryTime                   pgtype.Float8    `json:"mid_expiry_time"`
	Otp                             pgtype.Text      `json:"otp"`
	OtpExpireTime                   pgtype.Timestamp `json:"otp_expire_time"`
	Nid                             pgtype.Text      `json:"nid"`
	OtpAttempts                     pgtype.Int8      `json:"otp_attempts"`
	Vmsisdn                         pgtype.Text      `json:"vmsisdn"`
	BRepresentativeNo               pgtype.Text      `json:"b_representative_no"`
	BTinNo                          pgtype.Text      `json:"b_tin_no"`
	Bnid                            pgtype.Text      `json:"bnid"`
	BusinessType                    pgtype.Text      `json:"business_type"`
	ConnectivityIp                  pgtype.Text      `json:"connectivity_ip"`
	ConnectivityType                pgtype.Text      `json:"connectivity_type"`
	DefaultLongCode                 pgtype.Text      `json:"default_long_code"`
	FailedAttempt                   pgtype.Int4      `json:"failed_attempt"`
	ForcePwChanged                  pgtype.Int4      `json:"force_pw_changed"`
	AccountNonLocked                pgtype.Bool      `json:"account_non_locked"`
	IsClientPendingForAdminApproval pgtype.Bool      `json:"is_client_pending_for_admin_approval"`
	IsPolicyChecked                 pgtype.Bool      `json:"is_policy_checked"`
	KamOne                          pgtype.Text      `json:"kam_one"`
	KamTwo                          pgtype.Text      `json:"kam_two"`
	KamTypeOne                      pgtype.Text      `json:"kam_type_one"`
	KamTypeTwo                      pgtype.Text      `json:"kam_type_two"`
	Last5Pswd                       pgtype.Text      `json:"last_5_pswd"`
	LastAtmtTime                    pgtype.Timestamp `json:"last_atmt_time"`
	MoPort                          pgtype.Text      `json:"mo_port"`
	OtpExpTimeMs                    pgtype.Int8      `json:"otp_exp_time_ms"`
	UpdatedBy                       pgtype.Int8      `json:"updated_by"`
	FinTeamEmail                    pgtype.Text      `json:"fin_team_email"`
	DataCampID                      pgtype.Int8      `json:"data_camp_id"`
}
