// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	CallProcessNumbersCpApiS(ctx context.Context, arg CallProcessNumbersCpApiSParams) (CallProcessNumbersCpApiSRow, error)
	GetUser(ctx context.Context, username string) (GetUserRow, error)
}

var _ Querier = (*Queries)(nil)
